name: "ci-cd"
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_WEB: ghcr.io/${{ github.repository }}/web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: echo ${{ github.repository }}
      - name: Docker build and push
        run: |
          docker build -t $IMAGE_WEB:latest -f apps/web/Dockerfile .
          docker push $IMAGE_WEB:latest
